- .codeclimate.yml
[TP Card: 8441](https://moneyadviceservice.tpondemand.com/entity/8841-create-a-repo-for-fincap)
Adds Code Climate configuration for FinCap project.
> [DEV APPROVED] Adds Code Climate configuration

- README.md
- app/controllers/styleguide_controller.rb
- app/helpers/styleguide_helper.rb
- app/views/styleguide/colours.html.erb
- app/views/styleguide/latestnews.html.erb
Dries up the views for colours and for latest news.
> [DEV APPROVED] Refactor markup for some styleguide pages

- app/assets/stylesheets/components/ui/_hero.scss
- app/views/styleguide/hero.html.erb
Adds ability to add paragraphs and lists to general hero components
| Screenshot |
|![image](https://user-images.githubusercontent.com/13165846/36534170-adb08dd2-17bd-11e8-956a-68d5cf3a9c71.png)|
> [DEV APPROVED]- Hero custom content

- app/assets/stylesheets/components/ui/_large_cta.scss
Updates large call to action external link to follow same logic as general external links.
This component uses a different icon than the global external link detection, in a different position.
> Updates Large CTA with new external link detection

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/ui/_teaser.scss
- app/controllers/styleguide_controller.rb
- app/helpers/styleguide_helper.rb
- app/views/styleguide/buttons.html.erb
- app/views/styleguide/teaser.html.erb
It has been difficult to identify which buttons are primary and secondary given the diversity of information provided.
This PR adds the buttons page to the styleguide.
| Screenshot |
|------------|
|![image](https://user-images.githubusercontent.com/13165846/36592902-83b491cc-188f-11e8-917b-c806eb25802b.png)|
> [DEV APPROVED] Adds buttons to styleguide

- Gemfile.lock
- README.md
- hooks/pre-push
- test.sh
**No TP cards** but it is a dependency for the card [8794](https://moneyadviceservice.tpondemand.com/entity/8794-evhub-insight-summary-page-website-view).
So since we will start to add a lot of features to this repo I decided to add the git hook and the instruction on how everyone can install on their machines so we can make sure that the PR has everything passing. I know we have the continuous integration but is good to do our part as well before reaching the CI.
**By the way, the brakeman is failing on this branch until #28 is merged!**. So please review the #28 before reviewing this so that everything passes.
> [DEV APPROVED] Add test.sh and git pre-push hook

- README.md
This PR corrects some initial assumptions we had about the FinCap application. I am updating the README accordingly to communicate the rectifications.
> [DEV APPROVED] Updates usage instruction

- .gitignore
- Gemfile
- README.md
- app/assets/javascripts/application.js
- app/assets/javascripts/require_config.js.erb
- bower.json.erb
- config/initializers/assets.rb
[TP9009](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=task/9009&appConfig=eyJhY2lkIjoiOThBNEI1MURGODY0REREODQ4Qjk2MkE1RUY4NTRBMTIifQ==)
This PR adds RequireJS to FinCap so that it can be used to load JS components, initially the Nav and other useful components such as Dough utilities.
> 9009 add requirejs

- app/assets/stylesheets/base/_forms.scss
- app/assets/stylesheets/components/ui/_search.scss
- app/assets/stylesheets/components/ui/_sidepanel.scss
- app/helpers/styleguide_helper.rb
- app/views/shared/footer/_footer_search.html.erb
- app/views/styleguide/buttons.html.erb
- app/views/styleguide/forms.html.erb
- app/views/styleguide/sidepanel.html.erb
In order the keep the styleguide accurate, some additional work has been done in this PR to align the styleguide with the work recently completed.
Updates the buttons page on the styleguide to include the full-width modifier added recently
Specific styles for forms removed and replaced with general styles, visually still the same but styles will apply everywhere.
> Updates styleguide based on recent work

- test.sh
**No Tp cards**.
My hooks had failing tests because bower assets were not being loaded. 
Fixed by adding to test.sh.
> [DEV APPROVED] Add bowndler to test.sh

- Gemfile
- app/assets/javascripts/application.js
- bower.json.erb
- config/initializers/assets.rb
[TP9011](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=task/9011&appConfig=eyJhY2lkIjoiOThBNEI1MURGODY0REREODQ4Qjk2MkE1RUY4NTRBMTIifQ==)
This PR adds the necessary files to enable Dough JS components to be used in the project. This includes utilities and mediaQueries which are required for the Nav component.
> [DEV APPROVED] TP: 9034, Comment: sets up project to use Dough JS Components

- .gitignore
- package-lock.json
- package.json
- spec/javascripts/karma.conf.js
- spec/javascripts/test-main.js
- test.sh
[TP: 9035](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=task/9035&appConfig=eyJhY2lkIjoiOThBNEI1MURGODY0REREODQ4Qjk2MkE1RUY4NTRBMTIifQ==)
This PR adds Karma to the FinCap project to enable the addition of tests of JavaScript components.
> TP: 9035, Comment: Adds Karma to project

- app/assets/stylesheets/components/ui/_all.scss
- app/assets/stylesheets/components/ui/_coloured_box.scss
- app/helpers/styleguide_helper.rb
- app/views/styleguide/coloured_box.html.erb
Creates a new UI component in the fincap styleguide.
The new component consists of a box with a solid background colour, a heading and content, which is a list.
| Screenshot |
|![image](https://user-images.githubusercontent.com/13165846/37094571-32dfa55e-220b-11e8-8a7c-2a404f356771.png)|
> 9052 - Coloured box UI component

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/ui/_bordered_box.scss
- app/assets/stylesheets/components/ui/_large_cta.scss
- app/assets/stylesheets/components/ui/_teaser.scss
- app/assets/stylesheets/lib/_row.scss
- app/views/shared/footer/_footer.html.erb
I created a test page and populated it with some of the components, which highlighted some issues around spacing in the CSS, this PR addresses these issues to reduce the number of issues once we start putting views together.
> Tidies some CSS, ensures accurate spacing

- app/assets/stylesheets/base/_typography.scss
- app/presenters/evidence_summary_presenter.rb
- app/views/evidence_hub/index.html.erb
- app/views/insights/show.html.erb
- app/views/shared/_evidence_hub_hero.html.erb
Makes some adjustments to the insights pages UI.
> Updates insights page UI

- .rubocop.yml
- Dockerfile
- Jenkinsfile
- config/database-jenkins.yml
- docker-compose.yml
- script/docker_test
- script/test
**Adding the Test stage**
Introducing the test stage into Jenkins pipeline.
**Exclude node_modules Rubocop**
I have added an exclusion for the node_modules directory as it was flagging an error.
**Karma tests for informational purposes**
I have set the Karma tests to run for information only, as there are currently no scripts attached, to prevent it failing the Jenkins job.
> Add to Jenkins CI

- app/assets/stylesheets/components/ui/_all.scss
- app/assets/stylesheets/components/ui/_evaluation_types.scss
- app/assets/stylesheets/components/ui/_search_results.scss
- app/helpers/styleguide_helper.rb
- app/views/shared/_evaluation_types.html.erb
- app/views/styleguide/evaluation_types.html.erb
- app/views/styleguide/search_results.html.erb
Adds evaluation types component, and updates search results with ui component dependencies.
**Also**: Updates the search results with the updates evaluation type icons.
| Screenshot |
|------------|
|![image](https://user-images.githubusercontent.com/13165846/37602613-9bb1eac4-2b84-11e8-8047-250b80cc4367.png)|
> [DEV APPROVED] Adds evaluation types component

- app/views/shared/_feedback.html.erb
- app/views/styleguide/feedback.html.erb
| Screenshot |
|---------|
|![image](https://user-images.githubusercontent.com/13165846/37971413-c5f56ba4-31cd-11e8-9e2f-5e0e844e2d92.png)|
> [DEV APPROVED] Puts feedback UI component into partial, accepts values

- config/initializers/assets.rb
This PR adds fonts to the asset pipeline for deployment.  Hopefully fixing a current issue.
> [DEV APPROVED] Adds fonts to asset pipeline

- app/assets/javascripts/components/Nav.js
- app/assets/javascripts/require_config.js.erb
- spec/javascripts/tests/Nav_A11Y_spec.js
- spec/javascripts/tests/Nav_spec.js
[TP9041](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=userstory/9041&appConfig=eyJhY2lkIjoiOThBNEI1MURGODY0REREODQ4Qjk2MkE1RUY4NTRBMTIifQ==)
This PR adds to [PR#108](https://github.com/moneyadviceservice/fin_cap/pull/108) to add further accessibility, specifically keyboard support. 
- Adds keyboard interactions  to Levels 1/2 - left/right/up/down arrow keys
- Adds keyboard interactions to Levels 1/2 - enter/spacebar keys
- Adds keyboard interactions to Levels 1/2 - tab key
- Adds keyboard interactions to Levels 1/2 - escape key
- Adds keyboard interactions to Level 3 - left/right/up/down arrow keys
> [DEV APPROVED] TP: 9041, Comment: Adds A11Y to nav component - keyboard support

- app/assets/javascripts/components/Nav.js
- app/assets/javascripts/require_config.js.erb
- spec/javascripts/tests/Nav_A11Y_spec.js
- spec/javascripts/tests/Nav_spec.js
- Adds keyboard interactions - left/right arrows
- Adds keyboard interactions - enter, spacebar, down arrow keys
- Adds keyboard interactions - tab key
- Extends keyboard interactions - down arrow key
- Adds keyboard interactions - up arrow
- Extends keyboard interactions - right arrow key
- Extends keyboard interactions - left arrow key
- Adds keyboard interactions - escape key
- Extends keyboard interactions - down arrow key
- Extends keyboard interactions - up arrow key
- Extends keyboard interactions - tab key
- Extends keyboard interactions - right arrow key
- Extends keyboard interactions to Level 3 - right arrow key
- Extends keyboard interactions to Level 3 - left arrow key
- Extends keyboard interactions to Level 3 - down arrow key
- Extends keyboard interactions to Level 3 - up …
> TP: 9041, Comment: Adds A11Y to nav component - keyboard support

- app/assets/stylesheets/components/_icons.scss
- app/assets/stylesheets/components/ui/_evaluation_types.scss
- app/helpers/styleguide_helper.rb
- app/views/evidence_summaries/_content.html.erb
- app/views/shared/_evaluation_types.html.erb
- app/views/styleguide/info_icon.html.erb
[TP8937](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8937)
This makes any required Frontend changes to the content that is returned from the CMS to ensure that the look and feel of this page is as expected. 
**Desktop view:** 
**Mobile view:**
> [DEV APPROVED] 8937/8793 Evhub: Insight/Evaluation summary pages

- spec/javascripts/fixtures/Header.html
- spec/javascripts/tests/Header_spec.js
[TP9182](https://moneyadviceservice.tpondemand.com/entity/9182-fincap-header) - Header
[TP9232](https://moneyadviceservice.tpondemand.com/entity/9232-add-tests-for-header-front-end) - Tests task
This PR includes the tests for the header component, originally removed as adding dough config broke them.
> 9182 header tests

- features/support/env.rb
- spec/rails_helper.rb
Forgot to add this test support for Cucumber
> [DEV APPROVED] Add mas-cms-client test support

- app/assets/javascripts/components/Filters.js
- app/assets/javascripts/require_config.js.erb
- app/assets/stylesheets/components/ui/_sidepanel.scss
- app/views/evidence_hub/_checkboxes.html.erb
- app/views/evidence_hub/_filters.html.erb
- app/views/evidence_hub/_radio_buttons.html.erb
- app/views/evidence_hub/_search_form.html.erb
- spec/javascripts/fixtures/Filters.html
- spec/javascripts/test-main.js
- spec/javascripts/tests/Filters_spec.js
[TP9159](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/9159)
This adds a JS component to refresh the page when one of the filters is changed so that the new set of results is displayed. 
**No filter**
**Filter selected**
> [DEV APPROVED] 9159 filter component

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/ui/_all.scss
- app/assets/stylesheets/components/ui/_pagination.scss
- app/helpers/styleguide_helper.rb
- app/presenters/evidence_summaries_presenter.rb
- app/views/evidence_hub/index.html.erb
- app/views/styleguide/pagination.html.erb
- config/locales/en.yml
- spec/presenters/evidence_summaries_presenter_spec.rb
[TP9208](https://moneyadviceservice.tpondemand.com/entity/9208-styleguide-pagination-ui)
This PR adds pagination to the styleguide and also updates the evaluation hub to use the same pagination
> 9208 pagination ui

- app/assets/stylesheets/base/_body.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_header.scss
- app/assets/stylesheets/components/nav/_nav_level_1.scss
- app/assets/stylesheets/components/nav/_nav_level_2.scss
- app/assets/stylesheets/components/nav/_nav_level_3.scss
- app/assets/stylesheets/components/ui/_coloured_box.scss
- app/assets/stylesheets/components/ui/_hero.scss
- app/assets/stylesheets/components/ui/_teaser.scss
- app/assets/stylesheets/layout/_constrained.scss
- app/assets/stylesheets/layout/common/_2_col.scss
- app/assets/stylesheets/layout/common/_3_col.scss
- app/assets/stylesheets/lib/_grid.scss
- app/assets/stylesheets/lib/_row.scss
- app/assets/stylesheets/lib/_variables.scss
- app/assets/stylesheets/page_specific/_styleguide.scss
- app/views/components/_hero.html.erb
- app/views/evidence_hub/index.html.erb
- app/views/evidence_summaries/show.html.erb
- app/views/fincap_templates/index.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/_nav.html.erb
- app/views/styleguide/layout.html.erb
[TP9298](https://moneyadviceservice.tpondemand.com/entity/9298-apply-consistent-margins)
This PR is a big bit of work tidying up the margins and spacing used in the site to be more consistent, and less dependant on using lots of general styling classes in the markup.
Also updated the grids to go to the edge of it's container, removing the extra spacing wherever they were used.
> [DEV APPROVED] 9298 site margins

- app/assets/stylesheets/base/_body.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_list.scss
- app/assets/stylesheets/components/nav/_nav_level_2.scss
- app/assets/stylesheets/components/ui/_bordered_box.scss
- app/assets/stylesheets/components/ui/_download_box.scss
- app/assets/stylesheets/components/ui/_teaser.scss
- app/assets/stylesheets/layout/common/_2_col.scss
- app/assets/stylesheets/layout/common/_3_col.scss
- app/views/lifestages/_teaser_box.html.erb
- app/views/regional_strategies/show.html.erb
- app/views/styleguide/teaser.html.erb
Styling for [TP9244](https://moneyadviceservice.tpondemand.com/entity/9244-regional-strategy-page-view)
Aligned the current build to work better with existing styleguide and styles.
**NOTE:** Failing tests will be addressed by margo in the parent branch
> [DEV APPROVED] 9244 regional strategy page frontend

- app/views/homepages/show.html.erb
[TP 9261](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/9261)
This pr adds the final components to the homepage view - 2 large buttons, both have static content and links.
> [DEV APPROVED] - Homepage enhancement

- app/assets/stylesheets/base/_body.scss
[TP 9425](https://moneyadviceservice.tpondemand.com/entity/9425-replicate-the-formatting-of-the-current)
This is the second part of the fix provided here: https://github.com/moneyadviceservice/cms/pull/476
Co-Authored-By: Tomas D'Stefano <tomas_stefano@successoft.com>
> [DEV APPROVED] - 9425 Fix nested bullets indentation

- features/homepage.feature
- features/step_definitions/homepage_steps.rb
- features/support/ui/pages/home.rb
- spec/cassettes/fincap_cms/get/api/en/articles/our-approach_json.yml
- spec/cassettes/fincap_cms/get/api/en/homepages/root_json.yml
TECH DEBT
Further to the conversation on [this pr](https://github.com/moneyadviceservice/cms/pull/478), this pr adds an additional test for the homepage, which should have been added as part of pr #174.
> [DEV APPROVED] Add test for call to action buttons on homepage

- docker-compose.yml
Add Algolia search environmental vars to docker-compose required for Jenkins CI.
> Algolia search environment variables for Jenkins

- app/controllers/what_works_controller.rb
- app/presenters/article_template_presenter.rb
- app/presenters/homepage_template_presenter.rb
- app/presenters/lifestage_template_presenter.rb
- app/presenters/regional_strategy_template_presenter.rb
- app/presenters/shared_components/horizontal_teaser.rb
- app/presenters/shared_components/steering_group.rb
- app/presenters/shared_components/strategy.rb
- app/presenters/shared_components/teaser.rb
- app/presenters/what_works_template_presenter.rb
- app/templates/what_works_template.rb
- app/views/what_works/_supplementary_content.html.erb
- app/views/what_works/show.html.erb
- config/initializers/mas_cms_client.rb
- config/routes.rb
- features/step_definitions/lifestage_steps.rb
- features/step_definitions/shared_page_steps.rb
- features/step_definitions/what_works_steps.rb
- features/support/ui/pages/what_works.rb
- features/support/world/pages.rb
- features/what_works_page.feature
- spec/cassettes/fincap_cms/get/api/en/what_works/what-works-1_json.yml
[TP Card](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/9404)
- A new page type 'What works' has been added to the CMS. This PR
adds all the Rails piping to retrieve and display the page type.
- What works and lifestages' presenters had some common behaviour that did not match the inheritance pattern and could create confusion. We decided to extract the methods to a shared components folder. What do you think?
> [DEV APPROVED] 9404 - Add what Works Page

- app/assets/stylesheets/base/_typography.scss
- app/views/static_pages/impact_principles.html.erb
- features/impact_principles.feature
- features/step_definitions/impact_principles_steps.rb
- features/support/ui/pages/impact_principles.rb
- features/support/world/pages.rb
[TP 9568](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiNzEyRUZDMzlENEJERUE4QjJBRDVEQzdENUE1MEE2OEIifQ==&boardPopup=userstory/9568/silent)
- update call to action link from placeholder to uk-strategy page
- update download box link from placeholder to the Evidence and Evaluation Strategy Extract pdf 
- correct the capitalisation of the call to action text
> [DEV APPROVED] Amend impact principles view:

- config/environments/production.rb
[Tp Card](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/9609)
- This PR replaces the GTM tracking ID with the correct one for the FinCap project
> [DEV APPROVED][9609] Add correct GTM tracking ID

- app/views/lifestages/show.html.erb
- features/lifestage_page.feature
- features/what_works_page.feature
- spec/cassettes/fincap_cms/get/api/en/lifestages/young-adults_json.yml
- spec/cassettes/fincap_cms/get/api/en/news_jsondocument_type_news_order_by_date_true_tag_mobile-payments.yml
[TP 9582](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiNzEyRUZDMzlENEJERUE4QjJBRDVEQzdENUE1MEE2OEIifQ==&searchPopup=userstory/9582)
- Update cassettes because there was only 1 news item tagged to appear
- Update test data as seeds have been updated previously
> [DEV APPROVED] Only show 1 news item on Lifestage pages

- app/views/shared/nav/_nav.html.erb
[TP 9620](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/9283&searchPopup=userstory/9620)
- add additional items
- change some text
- update some links
> [DEV APPROVED] Change some of the navigation items

- app/controllers/thematic_reviews_controller.rb
- app/presenters/template_presenter.rb
- app/views/evidence_hub/index.html.erb
- app/views/fincap_templates/index.html.erb
- app/views/news/index.html.erb
- app/views/static_pages/be_involved.html.erb
- app/views/static_pages/impact_principles.html.erb
- config/locales/en.yml
- spec/presenters/template_presenter_spec.rb
[TP 10157](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10157/silent)
Add page titles to certain pages.
Refer to the commit message for full details of the solution.
> [DEV APPROVED] 10157 Set a page title for specific pages

- app/assets/stylesheets/components/_footer.scss
- app/views/shared/footer/_footer.html.erb
- app/views/shared/footer/_footer_menu.html.erb
- config/locales/en.yml
[tp 10126](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10126/silent)
Add a copyright notice in the footer
- Use translations for the text
- Update the alt tag on the sfgb logo because it was using a non-existent translation key
> [DEV APPROVED] 10126 Copyright notice

- Gemfile.lock
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/ui/_cookie.scss
- app/views/shared/_header.html.erb
- app/views/shared/footer/_footer.html.erb
- config/locales/en.yml
- features/cookie_policy_acceptance.feature
[TP 10620](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10620/silent)
In line with changes on the MAS site and legal requirements, the acceptance of cookies must be more explicit. Replace the cross with a button and move the request for consent to the bottom of the
page. The text has also changed.
> [DEV APPROVED] 10620 Cookie message

- .github/workflows/ci.yml
- app/views/layouts/application.html.erb
Results are being indexed higher than production and this is causing issues with SEO.
> Exclude robots when the env flag is set
