app/assets/stylesheets/components/ui/_all.scss
app/assets/stylesheets/components/ui/_bordered_box.scss
app/views/styleguide/_menu.html.erb
app/views/styleguide/borderedbox.html.erb

[TP Ticket 8923](https://moneyadviceservice.tpondemand.com/entity/8923-styleguide-ui-component-bordered-box)
Add the bordered box UI component for the new fincap website.  Uses flexbox for heights when 2 are side by side (Looks to be a common scenario)

8923 - bordered box component

---

app/assets/stylesheets/components/_all.scss
app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/ui/_all.scss
app/assets/stylesheets/components/ui/_sidepanel.scss
app/controllers/styleguide_controller.rb
app/views/styleguide/sidepanel.html.erb

[TP Ticket 8978](https://moneyadviceservice.tpondemand.com/entity/8978-styleguide-ui-component-evidence-hub-key)
Adds sidepanel UI component to the fincap styleguide.
This component is to be used in multiple places, including search and also insight and evaluation pages.  Therefore it shows how to construct the sidepanel for any instance.
This PR also includes some base button styles, a full PR for buttons will be included in an additional PR shortly.
**This PR includes:**
- Addition of the sidepanel page
- Adds new page to styleguide navigation
- Displays how each content element will be displayed
- Shows an example of a complete sidepanel
| Screenshot |
|![image](https://user-images.githubusercontent.com/13165846/36417414-cf6a5084-1623-11e8-9d9b-7e8b8474bad7.png)|

[DEV APPROVED] 8978 - Sidepanel UI Component

---

app/assets/stylesheets/components/ui/_all.scss
app/assets/stylesheets/components/ui/_search_results.scss
app/controllers/styleguide_controller.rb
app/helpers/styleguide_helper.rb
app/views/styleguide/_menu.html.erb
app/views/styleguide/search_results.html.erb

This PR is related to ticket [8773](https://moneyadviceservice.tpondemand.com/entity/8773-evhub-resultssearch-page-insights) and adds the UI elements, example markup and CSS to create the search results.
| Screenshot |
|![image](https://user-images.githubusercontent.com/13165846/36490205-ad796512-171f-11e8-81d2-461e6d4cbe93.png)|

[DEV APPROVED] 8773 (supporting task) - Adds search results UI

---

app/assets/stylesheets/base/_typography.scss

This PR makes a minor improvement to the CSS selector for detecting an external link.
The current solution is not specific enough and does not provide enough flexibility:
```
:not([href*="#{$site}"])
```
The problem with the above line of CSS is that any link which doesn't include fincap.org.uk is treated as an external link, this **includes** internal links like ``/contact-us``
The new solution is more specific:
```
[href^="http:"]:not([href*="#{$site}"]),
[href^="https:"]:not([href*="#{$site}"])
```
The rule now evaluates any link URL, and if it contains http:// or https:// **AND** isn't pointing to fincap.org.uk it will be treated as an external link:
I have tested this with below URL's all return the correct result:
- /contact-us
- /
- https://ww.fincap.org.uk
- http://fincap.org.uk
- …

[DEV APPROVED] Refactor external links css

---

app/assets/stylesheets/components/ui/_search_results.scss

Improves the display of the i icon on the search results evidence type.  The 'i' now better placed and more prominent.

Search results 'i' icon improvement

---

config/cucumber.yml

**No ticket** - But I am dependent of this fix for [8794](https://moneyadviceservice.tpondemand.com/entity/8794-evhub-insight-summary-page-website-view) card.
As far I understood, the cucumber rerun config does not work with not @wip. 
So since we are not using wip tags neither the rerun, removing the buggy config, makes the cucumber pass.

Removed buggy config on cucumber

---

.rspec
app/controllers/styleguide_controller.rb
spec/controllers/styleguide_controller_spec.rb

**No cards** but it is a dependency of the card [8794](https://moneyadviceservice.tpondemand.com/entity/8794-evhub-insight-summary-page-website-view) that I am working at the moment.
Be careful when you render dynamic templates like: `render params[:page]` because this dynamic render probably can add *security vulnerabilities*.
Such a simple code snippet **could** provided the ability for an attacker to read our source code and application configuration values.
Or depending the ability of the attacker, it could use this vulnerability to traverse directory on the server.
So validating the template before it renders it is the secure way to dynamic render the templates.
**Other observation is that on the code you can see that I added the render body: nil, status: 404. That's because we don't …

Validate before dynamic render the page

---

.gitignore
README.md

This PR ensures that the `.env` file is never checked in. This should prevent security-sensitive information from being leaked. It also contains instructions in the READ on how get up an running by setting up your environmental variable file.

Updates README with env var config setup

---

Gemfile
Gemfile.lock
spec/rails_helper.rb
spec/support/vcr.rb

[TP task](https://moneyadviceservice.tpondemand.com/entity/9016-add-the-documentall-call-to-fincap) from [TP card](https://moneyadviceservice.tpondemand.com/entity/8773-evhub-resultssearch-page-insights)
This is a dependency for [8773 TP card](https://moneyadviceservice.tpondemand.com/entity/8773-evhub-resultssearch-page-insights) and [8794 card](https://moneyadviceservice.tpondemand.com/entity/8794-evhub-insight-summary-page-website-view)
Setup VCR so VCR can record future cassettes when requesting to Fincap CMS.

9016 - Setup VCR for recording requests from Fincap CMS

---

Gemfile.lock
app/helpers/application_helper.rb
app/presenters/base_presenter.rb
spec/helpers/application_helper_spec.rb

[TP task](https://moneyadviceservice.tpondemand.com/entity/9017-format-for-displaying) from [TP card](https://moneyadviceservice.tpondemand.com/entity/8773-evhub-resultssearch-page-insights)
This is a dependency for [8773 TP card](https://moneyadviceservice.tpondemand.com/entity/8773-evhub-resultssearch-page-insights) and [8794 card]
I was working on adding the search results on evidence hub summaries which I came to a point that I need refactor the [view](https://github.com/moneyadviceservice/fin_cap/blob/9017-evidence-hub-summaries/app/views/evidence_hub/index.html.erb#L15) **then I decided to open separated a PR which will only add the presenter base line.**

[DEV APPROVED] 9017 - Add base presenter layer to the application

---

features/support/env.rb

[TP task](https://moneyadviceservice.tpondemand.com/entity/9017-format-for-displaying) from [TP card](https://moneyadviceservice.tpondemand.com/entity/8773-evhub-resultssearch-page-insights)
This is a dependency for [8773 TP card](https://moneyadviceservice.tpondemand.com/entity/8773-evhub-resultssearch-page-insights) and [8794 card]
I decided to use the same config that is using on RSpec
to avoid duplication config across RSpec and Cucumber.
With this configuration, any request to CMS from the feature tests will record and use the cassettes.

[DEV APPROVED] Add VCR to feature testing.

---

app/models/evidence_summary.rb
spec/models/evidence_summary_spec.rb

[TP task](https://moneyadviceservice.tpondemand.com/entity/9017-format-for-displaying) from [TP card](https://moneyadviceservice.tpondemand.com/entity/8773-evhub-resultssearch-page-insights)
This is a dependency for [8773 TP card](https://moneyadviceservice.tpondemand.com/entity/8773-evhub-resultssearch-page-insights) and [8794 card]
Since the Mas cms client gemi s returning most of the fields in a block, I created a ruby class
on Fincap that organise the documents in a way for Fincap to use easily.
You can do with one document:
```
EvidenceSummary.new(document)
```
Or with many documents:
```
EvidenceSummary.map(Mas::Cms::Document.all)
```
This  new class is responsible for organising the fields that come from CMS in a way that represents the precise attributes to be used in evidence …

[DEV APPROVED] Add evidence summary model

---

app/controllers/evidence_hub_controller.rb
app/presenters/base_presenter.rb
app/presenters/evidence_summary_presenter.rb
app/views/evidence_hub/index.html.erb
config/locales/en.yml
features/evidence_hub_search.feature
features/step_definitions/evidence_hub/search_steps.rb
features/support/env.rb
features/support/ui/page.rb
features/support/ui/pages/evidence_summaries.rb
features/support/world/pages.rb
spec/presenters/evidence_summary_presenter_spec.rb

[TP task](https://moneyadviceservice.tpondemand.com/entity/9017-format-for-displaying) from [TP card](https://moneyadviceservice.tpondemand.com/entity/8773-evhub-resultssearch-page-insights)
This is a dependency for [8773 TP card](https://moneyadviceservice.tpondemand.com/entity/8773-evhub-resultssearch-page-insights) and [8794 card]
Please review #45 first so that I can base this PR on master.
This is the work of rendering the search results for the first time when the user enter the evidence hub page.
* This task is not the frontend part (even if I choose to use the styleguide) so I will not post here a screenshot of the page.
* On the presenter I prefer to maintain the I18n.t call using the same locale over and over ('evidence_hub.search_results.evidence_type') because on the other …

[DEV APPROVED] 9017 evidence hub summaries

---

app/assets/javascripts/application.js
app/assets/javascripts/components/Nav.js
app/assets/javascripts/require_config.js.erb
app/views/shared/_nav.html.erb

[TP9040](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/9040&appConfig=eyJhY2lkIjoiOThBNEI1MURGODY0REREODQ4Qjk2MkE1RUY4NTRBMTIifQ==)
This PR adds some Common Dough components to the basic Nav (along with some other components required by these), specifically: 
- componentLoader: loads this and any other components where required on page load
- DoughBaseComponent: initialises the component
- utilities: used by the Nav to implement the Dough debounce utility
- mediaQueries: used by the Nav to implement the Dough atSmallViewport utility

[DEV APPROVED] - 9033 add dough components to nav

---

Gemfile
Gemfile.lock

**No TP cards**.
The master was failing because Dough was added without compatibility with Rails 5. 
[Dough 5.27 version](https://github.com/moneyadviceservice/dough/pull/300) adds Rails 5 compatibility, which fixes the compatibility error when you run `bundle install`

Update dough to 5.27

---

app/assets/stylesheets/components/ui/_teaser.scss
app/views/styleguide/teaser.html.erb

Adds the thematic review teaser box UI component for the new fincap website.
| Screenshot |
|![image](https://user-images.githubusercontent.com/13165846/37148078-0c17f99c-22c1-11e8-9351-91fed99f66a2.png)|

9037 - Adds new horizontal teaser box for thematic reviews

---

app/assets/stylesheets/components/ui/_teaser.scss
app/views/styleguide/teaser.html.erb

A small change to allow for the groups of teaser boxes to have a title
| screenshot |
|-----------|
|![image](https://user-images.githubusercontent.com/13165846/37205525-f6356818-238c-11e8-9352-20a4f7d0e435.png)|

[DEV APPROVED] Allows for the teaser box group to have a title

---

app/views/styleguide/layout.html.erb

This PR adds the 3 column layout example to the styleguide
| Screenshot |
|------------|
|![image](https://user-images.githubusercontent.com/13165846/37210340-4e9e4f98-23a0-11e8-90a3-ffc8f2a640be.png)|

Adds 3 column layout example to styleguide

---

app/models/evidence_summary.rb
app/presenters/evidence_summary_presenter.rb
app/views/evidence_hub/index.html.erb
config/locales/en.yml
spec/models/evidence_summary_spec.rb
spec/presenters/evidence_summary_presenter_spec.rb

[TP card](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/8794)
So now the evidence summary presenter will support both evidence summaries
page and the insight summary page because they are very similar.
The index page has this formatted:
%{Field Name}: #{Field value}
But the show action has:
%{Field Name}
%{Element one}
%{Element two}
in different ways. So in this line of thought I separated into three main methods
* The field name to be displayed. Used on the index and to be used in the show page. For this I added the I18n active model module so can help on this.
* The format of Field Name: field value that is used on index page
* Separated the strip tags for both index and show pages

[DEV APPROVED] 8794 Make evidence summary presenter more robust for Insight page

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/components/ui/_search_results.scss
app/assets/stylesheets/helpers/_all.scss
app/assets/stylesheets/helpers/_new.scss
app/assets/stylesheets/page_specific/_styleguide.scss
app/controllers/styleguide_controller.rb
app/helpers/styleguide_helper.rb
app/views/styleguide/_menu.html.erb
app/views/styleguide/new_label.html.erb

This PR adds a new UI helper to the styleguide, this is utilized by either:
**Using the class directly on the element**
```
<h2 class="is-new">Heading</h2>
```
**Extending the class for custom styles**
```
// Markup
<h2 class="heading heading--is-new">Heading</h2>
// SASS
.heading--is-new {
@extend .is-new;
// additional styles
}
```
| Screenshot |
|![image](https://user-images.githubusercontent.com/13165846/37333380-1e6e5986-26a1-11e8-88f1-ef35155176b6.png)|

9079 - Adds new label UI helper

---

app/models/evidence_summary.rb
app/presenters/evidence_summary_presenter.rb
app/views/evidence_hub/index.html.erb
app/views/insights/show.html.erb
config/locales/en.yml
features/insight_summary_page.feature
features/support/ui/pages/evidence_summary.rb
spec/models/evidence_summary_spec.rb
spec/presenters/evidence_summary_presenter_spec.rb

[TP card](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/8794)
So this PR adds the two sidepanel boxes for the insight page: the links to further information and contact details.
Obs.: There are three commits on this PR because it is waiting the PRs #60 and #59 to be merged first. After this two are merged there will be only one commit on this PR.

[DEV APPROVED] - 8794 add links and contact information

---

app/assets/stylesheets/components/_list.scss
app/views/styleguide/lists.html.erb

[TP 9080](https://moneyadviceservice.tpondemand.com/entity/9080-styleguide-lettered-list)
Adds a new list style to the fincap styleguide
| Screenshot |
|--------|
|![image](https://user-images.githubusercontent.com/13165846/37460992-e2d3b592-2844-11e8-8278-326a8b4ae2af.png)|

9080 - Adds lettered list to styleguide

---

docker-compose.yml

The test script was defined in the docker-compose.yml and in the Jenkinsfile test stage.  Two instances of the test script were therefore executed during the Jenkins job causing the following rake error;
`rails aborted!
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "pg_database_datname_index"
DETAIL:  Key (datname)=(fin_cap_test) already exists.`

Remove test script from docker-compose

---

app/views/evidence_hub/index.html.erb

Applies the evaluation types ui component to the search results (see: /styleguide/evaluation_types)
| Screenshot |
|![image](https://user-images.githubusercontent.com/13165846/37762753-239cc7e2-2db5-11e8-96a9-0d40a205626f.png)|

[DEV APPROVED] - Adds the evaluation types ui component to search results

---

Gemfile
app/assets/javascripts/application.js
app/views/layouts/application.html.erb
app/views/layouts/styleguide.html.erb

This PR removes turbolinks from the fincap project.  Turbolinks never call the documents ready event, causing problems for some of our JS components implemented via the dough component loader.
Basically we'd find that components won't kick in until the page is refreshed by the user.

[DEV APPROVED] Removes turbolinks from fincap project

---

app/views/shared/_large_cta.html.erb
app/views/styleguide/largecta.html.erb

This PR moves the markup for the large CTA component into a partial to be called with expected values.
A description on how to use this is added to the styleguide, screenshot below:
| Screenshot |
|![image](https://user-images.githubusercontent.com/13165846/37911559-43d68bdc-3108-11e8-8dfa-4382048fc164.png)|

[DEV APPROVED] DRYs up the large cta by moving markup into a partial

---

app/helpers/styleguide_helper.rb
app/views/shared/_life_stages.html.erb
app/views/styleguide/lifestages.html.erb
config/locales/en.yml

TP Ticket [9125](https://moneyadviceservice.tpondemand.com/entity/9125-create-a-reusable-lifestages-component-in)
Adds a new ui component to the fincap styleguide (/styleguide).  The links within this UI component will remain the same regardless of where it is used.
| Screenshot |
|------------|
|![life-stages-component](https://user-images.githubusercontent.com/13165846/38496592-101cce20-3bf6-11e8-9fab-ffafa4aa64c9.png)|

[DEV APPROVED] 9125 - Adds life stages as partial

---

app/views/shared/_country_list.html.erb
config/locales/en.yml

A little refactor to reduce markup in the country list ui component.

Refactors countries list component to use YAML, drys up markup

---

app/models/fincap_article.rb
app/presenters/article_presenter.rb
app/views/articles/show.html.erb
app/views/components/_feedback.html.erb
app/views/shared/_feedback.html.erb
config/locales/en.yml
features/article_page.feature
features/step_definitions/article_steps.rb
features/support/ui/pages/article.rb
spec/models/fincap_article_spec.rb
spec/presenters/article_presenter_spec.rb

[TP card](https://moneyadviceservice.tpondemand.com/entity/9162-fincap-article-page-view-or-add)
This PR adds the feedback box to article pages.

Add feedback component to article pages

---

app/assets/stylesheets/components/ui/_download_box.scss
app/assets/stylesheets/components/ui/_feedback_box.scss
app/assets/stylesheets/helpers/_all.scss
app/assets/stylesheets/helpers/_vertical_spacing.scss

Currently the article page ui components are bunched together with no space, this PR fixes this by adding a new helper class which applies consistent vertical spacing.
| Screenshot |
|----------|
|<img src="https://user-images.githubusercontent.com/13165846/39305552-6b0eaa62-4955-11e8-8eb2-adf17ba92744.png" width="300" />|

Adds vertical spacing helper for article page right side components

---

app/assets/stylesheets/components/_list.scss

Adds a blue arrow to the grouped CTA list UI component.
| Before | After |
|-------|------|
|![image](https://user-images.githubusercontent.com/13165846/39309242-70a75564-495f-11e8-9f57-48d159d68702.png)|![image](https://user-images.githubusercontent.com/13165846/39309202-54e86750-495f-11e8-8169-2a93f16106c4.png)|

[DEV APPROVED] Adds arrows to grouped CTA list

---

app/views/shared/_evidence_types.html.erb
app/views/styleguide/evidence_types.html.erb

The evidence_type icon partial was using a nested paragraph tag which was not rendering correctly if the partial was called within a paragraph tag because HTML5 makes nested p tags illegal. Changing the paragraph tag to a span tag allows the partial to be called within a paragraph tag and correctly renders the icons inline with their corresponding text.
**BEFORE**
**AFTER**

Styleguide: Change nested paragraph tag to span tag

---

app/assets/javascripts/components/Nav.js
app/assets/stylesheets/components/nav/_nav_level_2.scss
app/views/shared/_nav.html.erb
spec/javascripts/fixtures/Nav.html
spec/javascripts/test-main.js
spec/javascripts/tests/Nav_A11Y_spec.js

[TP9041](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/9041&appConfig=eyJhY2lkIjoiOThBNEI1MURGODY0REREODQ4Qjk2MkE1RUY4NTRBMTIifQ==)
This PR addresses some of the additions in the ticket (WAI-ARIA roles, states and properties). A related PR ([#109](https://github.com/moneyadviceservice/fin_cap/pull/109)) adds keyboard enhancements to this. 
- Adds static ARIA roles/states/properties
- Adds dynamic ARIA states
- Adds static tabindex values
- Adds dynamic tabindex values
Additionally there is a further ticket to add the structure in the back end to replace the current markup.

TP: 9041, Comment: Adds A11Y to nav component - WAI-ARIA properties

---

app/controllers/evidence_hub_controller.rb
app/presenters/evidence_summary_presenter.rb
app/views/evidence_hub/_search_form.html.erb
app/views/evidence_hub/_search_result.html.erb
app/views/evidence_hub/index.html.erb
app/views/evidence_summaries/_content.html.erb
app/views/evidence_summaries/_evidence_checklist.html.erb
app/views/evidence_summaries/_evidence_type.html.erb
config/locales/en.yml
features/evaluation_summary_page.feature
features/insight_summary_page.feature
features/step_definitions/evidence_hub/show_steps.rb
features/support/ui/pages/evidence_summaries.rb
features/support/ui/pages/evidence_summary.rb
spec/presenters/evidence_summary_presenter_spec.rb

[TP card](https://moneyadviceservice.tpondemand.com/entity/9189-add-evaluation-checklist-to-the-evaluation) and [TP card](https://moneyadviceservice.tpondemand.com/entity/9167-display-qualitative-and-quantitative-data-types)
This PR adds the insight checklist and evaluation checklist to the respective individual pages.
So now the evidence hub controller inherits from evidence summaries controller
altogether with Insight and Evaluation.
**Which means any evidence summary page will have by default the checklist from the config/locales/en.yml.**
Also refactor the evidence hub index view to have a search form partial as
well as search result. I was not sure if I should be adding on the same PR but I kinda need to re-use the checklist for different page types so I decide to include on the PR. …

Add evidence type and evidence checlist to Insight & Evaluation

---

spec/rails_helper.rb

This change is being made as the env variable outside of test needs to
point to a live CMS url. Unfortunately at the moment there is no
consistent fincap cms url yet and so the VCRs are recorded pointing to
localhost

[DEV APPROVED] - Update mas-cms-client to use localhost in tests

---

app/presenters/evidence_summary_presenter.rb
app/views/evidence_summaries/_evidence_checklist.html.erb
spec/presenters/evidence_summary_presenter_spec.rb

Presenter tests were broken because the translations file had changed in structure. This pr amends the presenter tests to reflect the new structure.
Feature tests were breaking because the class for the particular data type was not hyphenated and therefore the css being looked for did not exist, i.e. `programme theory` instead of `programme-theory`.
I also changed the presenter method name to better reflect its changed responsibility.

Fix broken presenter tests and feature specs

---

app/assets/stylesheets/components/_list.scss

[TP9233](https://moneyadviceservice.tpondemand.com/entity/9233-bug-grouped-cta-list-text-overlap)
This PR moves the padding and border styles on the styleguide's list CTA to be on the li not the a, so that padding can be added to the sides of the a, which stops the text overlapping the arrow icon.
===
Before:
After:

[DEV APPROVED] 9233 Styleguide CTA List Bug

---

app/assets/stylesheets/components/ui/_search_results.scss

[TP9229](https://moneyadviceservice.tpondemand.com/entity/9229-bug-consistent-spacing-between-evidence-type)
This PR adds margin to the search result's evidence type
===
Before:
After:

[DEV APPROVED] 9229 Evidence Type spacing bug

---

app/assets/stylesheets/components/ui/_sidepanel.scss
app/views/evidence_hub/_filters.html.erb
app/views/evidence_hub/_radio_buttons.html.erb

[TP9207](https://moneyadviceservice.tpondemand.com/entity/9207-search-filter-radio-button-labels)
This PR moves the radio input inside the label so that clicking the label selects the radio button

[DEV APPROVED] 9207 Search filter radio label bug

---

app/assets/stylesheets/components/_icons.scss

[TP9228](https://moneyadviceservice.tpondemand.com/entity/9228-bug-evidence-type-i-icon-colour)
This PR adds in extra styling so that the I is still white after visiting link
Screenshots
===
Before:
After:

[DEV APPROVED] 9228 evidence i icon visited color bug

---

app/views/layouts/application.html.erb
app/views/layouts/styleguide.html.erb

[TP9236](https://moneyadviceservice.tpondemand.com/entity/9236-bug-viewport-meta-tag-missing)
This PR adds in the viewport meta tag so that the site scales correctly on mobile.
Screenshots
===
Before:
After:

9236 Missing viewport meta tag bug

---

app/presenters/evidence_summaries_presenter.rb
spec/presenters/evidence_summaries_presenter_spec.rb

[TP9234](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=bug/9234)
Currently, the pagination is always displayed regardless of the number of results returned from a search. 
This PR only displays the pagination when there are more than one page of results.

[DEV APPROVED] TP: 9234, Comment: Limits pagination display

---

app/views/styleguide/teaser.html.erb

Add page anchors to different teaser boxes to make more obvious that there are several variations of the teaser box UI component.
BEFORE
AFTER

[DEV APPROVED] UI addition to styleguide

---

app/views/shared/_feedback.html.erb
app/views/styleguide/feedback.html.erb

The styleguide link to the feedback component was erring due to an incorrectly named local being passed to the partial. 
Initially, the partial accepted 2 locals. At a later date, one of the locals was replaced by a translation key and the other local was renamed. The styleguide view was not updated accordingly.
Pass one correctly named local.

Fix styleguide feedback bug

---

Gemfile.lock

This PR updates brakeman from 4.3.0 to 4.3.1 as jenkins tests were failing on PRs with the message
`=== Running brakeman -q --no-pager --ensure-latest`
`Brakeman 4.3.0 is not the latest version 4.3.1`
`=== These tests failed.`

[DEV APPROVED] updated brakeman to stop failing jenkins tests on prs

---

app/assets/stylesheets/components/_list.scss
app/assets/stylesheets/layout/common/_2_col.scss
app/assets/stylesheets/layout/common/_3_col.scss
app/assets/stylesheets/lib/_grid.scss
app/controllers/styleguide_controller.rb
app/helpers/styleguide_helper.rb
app/views/lifestages/show.html.erb
app/views/shared/_research_and_evaluation.html.erb
app/views/styleguide/_menu.html.erb
app/views/styleguide/countries.html.erb
app/views/styleguide/layout.html.erb
app/views/styleguide/research_evaluation.html.erb
config/locales/en.yml
features/step_definitions/lifestage_steps.rb

[TP9295](https://moneyadviceservice.tpondemand.com/entity/9295-research-and-evaluation-solid-colour-box)
This PR 
1. tweaks the layout component in the styleguide to allow for equal heights (flex) columns and no margin on the columns on the edges (1&2 if there's 3 columns, 1&4 if there's 4 columns, etc.) so that the row fills available space. 
2. adds in the research and evaluation partial which uses this styling and is present on multiple pages, so far only the lifestyle page.

9295 research and evaluation partial

---

app/assets/stylesheets/components/ui/_latest_news.scss
app/presenters/latest_news_template_presenter.rb
app/views/components/_hero.html.erb
app/views/news/index.html.erb
app/views/styleguide/latestnews.html.erb
config/locales/en.yml
features/step_definitions/latest_news_page_steps.rb
spec/presenters/latest_news_template_presenter_spec.rb

[TP9305](https://moneyadviceservice.tpondemand.com/entity/9305-latest-news-view)
This PR adds a snippet variation of the latest news list to the styleguide
And then adds the styling for this into the news page
**NOTE:** The margins on the latest news list on the news page are not the same as the design. This is due to [TP9298](https://moneyadviceservice.tpondemand.com/entity/9298-apply-consistent-margins) which addresses the inconsistencies  in the margins

[DEV APPROVED] 9305 latest news frontend

---

features/lifestage_page.feature
features/step_definitions/lifestage_steps.rb

Does what it says on the tin. Because it refers to a local file, its failing on Go. It can be removed as the rest of the step satisfactorily tests the feature.

Remove test that relies on local file

---

Gemfile
Gemfile.lock
config/autoprefixer.yml

[TP9203](https://moneyadviceservice.tpondemand.com/entity/9203-add-prefixing-to-the-sass-compilation)
This PR adds the [autoprefixer-rails](https://github.com/ai/autoprefixer-rails/blob/master/README.md) gem which adds prefixing to any properties needed for our config (ie 9 and above) as based on [Can I use](https://caniuse.com/)
Use `rake autoprefixer:info` to see what will be prefixed
Use `rake tmp:clear` if update not being applied
To test, check that a property listed in the info rake is receiving prefixes. E.g. .header-content flex property

[DEV APPROVED] - 9203 CSS Prefix in SASS build

---

app/controllers/homepage_controller.rb
app/controllers/homepages_controller.rb
app/presenters/homepage_template_presenter.rb
app/templates/homepage_template.rb
app/views/homepage/index.html.erb
app/views/homepages/_horizontal_teaser.html.erb
app/views/homepages/show.html.erb
config/initializers/mas_cms_client.rb
config/routes.rb
features/homepage.feature
features/step_definitions/homepage_steps.rb
features/support/ui/pages/home.rb
features/support/world/pages.rb
spec/cassettes/fincap_cms/get/api/en/homepages/root_json.yml
spec/presenters/homepage_template_presenter_spec.rb
spec/templates/homepage_template_spec.rb

[TP 9261](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5481321774608038243&appConfig=eyJhY2lkIjoiNjRGM0FCMDY3RUQ5MDREM0RGNDZGOUM0REZENUZBMzIifQ==&searchPopup=userstory/9261)
The fincap website needs a homepage.
- direct the 'root' route to the homepages controller
- add template, presenter and view for the page
- add template and presenter methods for the horizontal teaser component
This pr makes use of the [cms pr](https://github.com/moneyadviceservice/cms/pull/465) which creates the homepage layout so editors can enter the content for this page.
There are 2 ways to handle the route for landing pages. 
1. set the slug for the specific page. The implication of this approach is:
-  the requirement for editors to use that slug/constant when creating or amending …

9261 Create homepage view

---

app/views/fincap_templates/show.html.erb
app/views/homepages/show.html.erb
app/views/lifestages/show.html.erb
app/views/news/show.html.erb

[TP9409](https://moneyadviceservice.tpondemand.com/entity/9409-add-body-content-class-to-content)
The body class body-content was created to add some padding to the body content and to put back in bullets so that they were visible when used in the wysiwyg in the CMS. 
This PR adds this class to articles, news, lifestages, and the homepage, as they were missing from the markup
**Before**:
**After**:

[DEV APPROVED] 9409 Adding missing body class

---

app/assets/stylesheets/base/_body.scss

[TP 9474](https://moneyadviceservice.tpondemand.com/entity/9474-bullet-points-formatting)
This PR fixes a formatting issue when displaying lists with bullets.
The issue is caused by the fact that the MAS editor _always_ wraps list items with a paragraph _when updating a published page with a list_ – this is a feature that has been like that this since forever.
Although, as a consequence of #175, by adding bullets to list items, we made it obvious to the point that we need to inline paragraphs inside list items.
Originally it was believed to be a backend bug, but it's an actual frontend display issue that can be fixed with some css.

[DEV APPROVED] 9474 Fix bullets formatting

---

app/views/evidence_summaries/_content.html.erb
app/views/shared/_evaluation_types.html.erb
features/evaluation_summary_page.feature
features/evidence_hub_search.feature
features/insight_summary_page.feature
features/review_summary_page.feature
features/step_definitions/evidence_hub/search_steps.rb
features/step_definitions/evidence_hub/show_steps.rb
features/support/ui/pages/evidence_summaries.rb
features/support/ui/pages/evidence_summary.rb

[TP 9459](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/9405&searchPopup=userstory/9459)
In the Evidence Hub page, the information icon should appear next to each summary. It should also appear on the evidence summary page. In all cases, the icon should link to the article page for the corresponding evidence type e.g. if the evidence summary is a review, the icon should link to the evidence-type-review article.

[DEV APPROVED] - Add info icon with correct link on the following pages:

---

app/controllers/uk_strategies_controller.rb
app/presenters/uk_strategy_template_presenter.rb
app/templates/uk_strategy_template.rb
app/views/uk_strategies/show.html.erb
config/initializers/mas_cms_client.rb
config/routes.rb
features/homepage.feature
features/lifestage_page.feature
features/step_definitions/lifestage_steps.rb
features/step_definitions/regional_strategy_steps.rb
features/step_definitions/shared_page_steps.rb
features/step_definitions/uk_strategy_steps.rb
features/support/ui/page.rb
features/support/ui/pages/regional_strategy.rb
features/support/ui/pages/uk_strategy.rb
features/support/world/pages.rb
features/uk_strategy_page.feature
spec/cassettes/fincap_cms/get/api/en/uk_strategies/uk-strategy_json.yml
spec/presenters/uk_strategy_template_presenter_spec.rb
spec/support/vcr.rb
spec/templates/uk_strategy_template_spec.rb

[TP 9246](https://moneyadviceservice.tpondemand.com/entity/9246-uk-strategy-page-view)
As a user visiting the fincap website, I need to be able to visit a landing page relating to the UK only, so that I can get information relating to where I live. This PR adds the view that presents the information retrieved from the `cms` – depends on [TP 9245](https://moneyadviceservice.tpondemand.com/entity/9245-cms-uk-strategy-page),  https://github.com/moneyadviceservice/cms/pull/478

[DEV APPROVED] - 9246 UK strategy page view

---

app/controllers/application_controller.rb
app/controllers/catch_all_controller.rb
config/routes.rb
features/redirect.feature
features/step_definitions/shared_page_steps.rb
spec/cassettes/fincap_cms/get/api/document/WOYJaysAADA42rIr/looking-after-the-pennies.yml
spec/cassettes/fincap_cms/get/api/document/WOuEzCsAAIaQ8tXy/financial-well-being-the-employee-view.yml
spec/cassettes/fincap_cms/get/api/document/WTVdRSkAAOsYaAQx/raising-household-saving.yml
spec/cassettes/fincap_cms/get/api/en/news/old-news_json.yml
spec/cassettes/fincap_cms/get/api/en/pages/changing-behaviour-around-online-transactions/preview.yml
spec/cassettes/fincap_cms/get/api/this-page-dont-exist-anywhere.yml
spec/cassettes/fincap_cms/get/api/young-adults.yml

[TP card](https://moneyadviceservice.tpondemand.com/entity/9225-implement-internal-redirect-feature-on-fincap)
The redirect mechanism is implemented as follows:
- The user visits a page that does not exist:
Fincap app will request to CMS if the page contains a redirect. If it does, it will redirect the user; if not normal Rails flow will follow.
- The user visits any supported page type but the page does not exist:
If there is a redirect on CMS, Fincap app will catch the redirect exception from mas-cms-client gem
and redirect the user to the destination specified on CMS.
In all other cases, the app will continue to run and will return the 'not found' page. 
This depends on this PR https://github.com/moneyadviceservice/cms/pull/480
Please review this PR as well.

[DEV APPROVED] Add redirect feature to fincap site

---

app/helpers/components_helper.rb
app/views/shared/_research_and_evaluation.html.erb
config/locales/en.yml
features/components/research_and_evaluation.feature
features/lifestage_page.feature
features/step_definitions/components/research_evaluation_steps.rb
features/support/ui/page.rb
spec/cassettes/fincap_cms/get/api/en/lifestages/young-adults_json.yml
spec/helpers/components_helper_spec.rb

[TP 9519](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5481321774608038243&appConfig=eyJhY2lkIjoiNjRGM0FCMDY3RUQ5MDREM0RGNDZGOUM0REZENUZBMzIifQ==&searchPopup=bug/9519)
The links on the research and evaluation boxes do not point to a valid path, consequently an error is rendered.
- correct text and slug in the translations file where they are defined
- add a page type
- use a helper method to define the correct path based on page type

[DEV APPROVED] 9519 Update links in the research and evaluation boxes

---

config/locales/en.yml
features/evidence_hub_search.feature
features/step_definitions/evidence_hub/show_steps.rb
features/support/ui/pages/evidence_summaries.rb

[TP 9294](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiNzEyRUZDMzlENEJERUE4QjJBRDVEQzdENUE1MEE2OEIifQ==&searchPopup=userstory/9492)
There are 2 filters for the Topic filter group which are essentially the same and one has no documents. If you click on 'pensions' no documents appear and it is a poor user experience.
Remove 'pensions' from the translations file.

[DEV APPROVED] Remove pensions from Topic filter options

---

config/locales/en.yml
features/evidence_hub_search.feature

[TP 9552](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiNzEyRUZDMzlENEJERUE4QjJBRDVEQzdENUE1MEE2OEIifQ==&searchPopup=bug/9552)
1. On the evidence hub search form, ticking the Client group search filters 'Parent/families' and 'Teachers/practitioners' do not returning correct results. 
1. When clicking on a filter in the Key Info panel for 'Parent / families' and 'Teachers / practitioners',
the corresponding filter on the search results page is not ticked.
Both these issues are a result of the values on the fincap form not matching the values in the cms blocks, there is a space either side of the `/` on the search form. The quick fix is to update the values in translations file to match the ones in cms.

[DEV APPROVED] - Fix for client group filters

---

README.md

- There was some reference to Foreman while the project has no procfile.
- More explicit examples for running FINCAP app in different port than
CMS.
- Fixed the command for starting CMS to work with Fincap.

Update Readme info for running the app locally

---

app/models/evidence_summary.rb
app/presenters/evidence_summary_presenter.rb
app/views/evidence_hub/_search_result.html.erb
app/views/evidence_summaries/_content.html.erb
spec/models/evidence_summary_spec.rb
spec/presenters/evidence_summary_presenter_spec.rb

[TP 8924](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5481321774608038243&appConfig=eyJhY2lkIjoiNjRGM0FCMDY3RUQ5MDREM0RGNDZGOUM0REZENUZBMzIifQ==&boardPopup=userstory/8924/silent)
Display evidence summaries and evidence hub search results with an indicator that allows users to identify which documents are new.
Specifically, evidence summaries which have been created less than 90 days ago will be styled with a 'new' tag. This tag should display on both the individual summary page and for each document in the search results, where appropriate.
- presenter method to check the created_at date for the content block
and returns the styleguide class or an empty string
- use the presenter method in the the search results and the evidence
summary views

[DEV APPROVED] Style evidence summaries to indicate if they are new or not

---

app/controllers/news_controller.rb
app/models/tagged_news.rb
config/initializers/mas_cms_client.rb
features/lifestage_page.feature
spec/cassettes/fincap_cms/get/api/en/news_jsondocument_type_news_keyword_2017_order_by_date_true.yml
spec/cassettes/fincap_cms/get/api/en/news_jsondocument_type_news_order_by_date_true.yml
spec/cassettes/fincap_cms/get/api/en/news_jsondocument_type_news_order_by_date_true_.yml
spec/cassettes/fincap_cms/get/api/en/news_jsondocument_type_news_order_by_date_true_tag_mobile-payments.yml
spec/models/tagged_news_spec.rb

[TP 9500](https://moneyadviceservice.tpondemand.com/entity/9500-latest-news-component-doesnt-show-most)+[TP 9551](https://moneyadviceservice.tpondemand.com/entity/9551-news-page-does-not-show-all)
This PR is an alternative fix to the issue in the card.
The idea is that you should be ordering upfront, in order to avoid issues with pagination and filtering of huge arrays in memory.
Requires: https://github.com/moneyadviceservice/cms/pull/486

[DEV APPROVED] Retrieve ordered news with an `order_by_date` parameter

---

.gitignore
app/assets/stylesheets/components/ui/_hero.scss

[9539]( https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiNzEyRUZDMzlENEJERUE4QjJBRDVEQzdENUE1MEE2OEIifQ==&boardPopup=bug/9539/silent)
Fix for this small defect, in Safari, it seems that the margin on the h1 gets ignored so the contain div does not display the background image.  To fix I removed the margin and added padding to the containing div.
Checked in FF, Safari and Chrome

[DEV APPROVED] 9539 Hero Images Safari Issue

---

app/views/static_pages/be_involved.html.erb
config/locales/en.yml

[TP9562](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiNzEyRUZDMzlENEJERUE4QjJBRDVEQzdENUE1MEE2OEIifQ==&boardPopup=bug/9562/silent)
Not all the links are available on localhost but they are not the prod version
Updated links and text as per ticket
Evaluation toolkit link goes to articles/evaluation-toolkit-overview
Item number 3 links to articles/talk-money-week
Item 4 text has changed to "Read our research and get updates from the steering group on our Lifestages pages, and don’t forget to follow the Strategy’s official Twitter and LinkedIn profile."

[DEV APPROVED] 9562 get involved page copy and link updates

---

app/assets/javascripts/components/Nav.js
app/assets/stylesheets/components/nav/_nav_level_2.scss
spec/javascripts/tests/Nav_spec.js

[TP9544](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=bug/9544/silent)
This PR is to enable the clickable functionality on the Life Stages links on all views and disable the third level of links on mobile (these will still be accessed from the landing pages). 
The tests associated with the now-redundant mobile view functionality are also removed.
Additionally there is a small visual change associated with this: I have removed the chevrons from the life stages links on the mobile view, which currently suggest a further level would be displayed.

[DEV APPROVED] 9544 nav life stages mobile view

---

app/views/shared/footer/_footer_newsletter.html.erb
config/locales/en.yml
features/homepage.feature
features/step_definitions/homepage_steps.rb
features/support/ui/pages/home.rb

[TP 9565](https://moneyadviceservice.tpondemand.com/entity/9565-change-email-subscribe-link-in-the)
This PR changes the subscription link in the footer and adds a regression test.

[DEV APPROVED] - 9565 Change subscribe link in the footer

---

app/controllers/evidence_hub_controller.rb
app/forms/evidence_summary_search_form.rb
app/services/evidence_hub/search_form_param_parser.rb
app/services/evidence_hub/year_of_publication_parser.rb
config/locales/en.yml
features/evidence_hub_search.feature
features/step_definitions/evidence_hub/search_steps.rb
features/support/ui/pages/evidence_summaries.rb
spec/cassettes/fincap_cms/get/api/en/documents_jsondocument_type_Evaluation_keyword_page_1_per_page_20.yml
spec/cassettes/fincap_cms/get/api/en/documents_jsondocument_type_Insight_document_type_Review_keyword_page_1_per_page_20.yml
spec/forms/evidence_summary_search_form_spec.rb
spec/services/evidence_hub/search_form_param_parser_spec.rb
spec/services/evidence_hub/year_of_publication_parser_spec.rb

[TP-9405](https://moneyadviceservice.tpondemand.com/entity/9405-add-evidence-type-to-ev-hub)
- We want to be able to filter the Evidence Hub results by the "Evidence type".
- This PR also includes some refactor in the Search Form Parser in order to isolate responsibilities and allow future extension of the class.
- I recommend to review it Commit by Commit.
Page to check: (`/en/evidence_hub`)

[DEV APPROVED] 9405 - Allow filter by Evidence type on Evidence Hub

---

app/views/evaluations/_activities_and_setting.html.erb
app/views/evaluations/_measured_outcomes.html.erb
app/views/evaluations/_programme_delivery.html.erb
features/evaluation_summary_page.feature
features/step_definitions/evidence_hub/show_steps.rb
spec/cassettes/fincap_cms/get/api/en/evaluations/evaluation-without-some-blocks_json.yml

[TP card](https://moneyadviceservice.tpondemand.com/entity/9493-remove-key-info-titles-if-empty)
Key info section headlines will sometimes show up even if there is nothing beneath them. We would like these headings to appear only if there is appropriate info to display for them.
Talking with Venetia she was specific to only add this logic to three fields:
Activity and settings
Measured outcomes
Programme delivered by

Show Key Info headings only if there is information beneath them

---

app/assets/javascripts/application.js
app/views/layouts/application.html.erb

[9567](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiNzEyRUZDMzlENEJERUE4QjJBRDVEQzdENUE1MEE2OEIifQ==&boardPopup=bug/9567/silent)
This PR updates the require js to pull in the require js at the bottom of the page.
The DOM should then be fully loaded before the contentLoader starts working. 
Putting the script for requirejs at the bottom of the page then the DOM content should be fully loaded, ie the html will be there and the contentLoader will be able to check for which elements need a script to be loaded to allow them to work.

Js load issue

---

app/views/shared/nav/_nav.html.erb

[9571](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiNzEyRUZDMzlENEJERUE4QjJBRDVEQzdENUE1MEE2OEIifQ==&boardPopup=userstory/9571/silent)
This PR is to remove the hard coded link to funding found in Research and Evaluation > Funding
**Old nav**
**New nav**

[DEV APPROVED] Remove hard coded funding link from main nav

---

app/views/layouts/application.html.erb
config/environments/production.rb

[9588](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/9588)
Added google tag managers to application.html.erb.
Followed the example in the [Frontend project](https://github.com/moneyadviceservice/frontend) rather than follow what was in the ticket.
Not sure if this can be tested except on production

[DEV APPROVED] Add Google tag manager top application.html.erb

---

spec/requests/evidence_hub_spec.rb
spec/services/evidence_hub/search_form_param_parser_spec.rb

To be consistent with the changes introduced with https://github.com/moneyadviceservice/fin_cap/pull/196 and https://github.com/moneyadviceservice/cms/pull/494.
Please note that this is not strictly required as the unit tests in subject are stubbing the response/checking the way the filtering works (hence no need to use real names).

[DEV APPROVED] - Align client groups checkbox option naming in unit tests

---

app/views/shared/footer/_footer_menu.html.erb

**Update footer links**
[9590](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiNzEyRUZDMzlENEJERUE4QjJBRDVEQzdENUE1MEE2OEIifQ==&boardPopup=userstory/9590/silent)
Removed links to site map and accessibility
Changed other links to use /en/article/somelink format

[DEV APPROVED] Remove site map and accessibility links

---

app/assets/stylesheets/components/nav/_nav_level_2.scss
app/assets/stylesheets/components/nav/_nav_level_3.scss
app/views/shared/nav/_level_2_subcategory_link.html.erb
app/views/shared/nav/_level_3_subcategory_link.html.erb

[9578](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiNzEyRUZDMzlENEJERUE4QjJBRDVEQzdENUE1MEE2OEIifQ==&boardPopup=userstory/9578/silent)
This PR is to prevent the subcategory links having the a visited colour of orange so that they can be distinguished from the heading links.
Added a class to the the subcategory links and kept the visited colour as the same blue as the default non-visited state
New state

[DEV APPROVED] Add class and style to level2 subcategory links

---

app/controllers/thematic_reviews_controller.rb
app/views/thematic_reviews/show.html.erb
features/thematic_review_page.feature

[TP 9560](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiNzEyRUZDMzlENEJERUE4QjJBRDVEQzdENUE1MEE2OEIifQ==&searchPopup=userstory/9560)
- Delete the api call for tagged news
- Remove the news partial from thematic reviews show view

[DEV APPROVED] Dont show news items on thematic review pages

---

app/assets/stylesheets/components/ui/_download_box.scss
app/assets/stylesheets/components/ui/_feedback_box.scss
app/assets/stylesheets/components/ui/_sidepanel.scss
app/views/fincap_templates/show.html.erb

[TP9587](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiNzEyRUZDMzlENEJERUE4QjJBRDVEQzdENUE1MEE2OEIifQ==&boardPopup=userstory/9587/silent)
This updates the display order of components on the Right Hand Side of the articles pages, which currently displays the Twitter feed in the wrong position. 
Additionally it adds some consistency to the vertical spacing of the components which is effected by this change. 
**Current**
**Updated**

[DEV APPROVED] TP9587, Comment: Updates display order of components

---

app/views/shared/_header.html.erb

- set the 'contact us' link in the header to the article page 'contact-us'

[DEV APPROVED] Update link in header

---

app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/components/ui/_search_results.scss
app/views/shared/_search.html.erb

[TP9589](https://moneyadviceservice.tpondemand.com/entity/9589-update-search-box-hint-text-and)
This PR 
- puts back the search svg icon into the search partial
- updates the search bar text
- tweaks styling to keep the search bar icon inside the bar on the search results page
It can be seen in the header (desktop and mobile), footer, and on the search results page
**PLEASE NOTE** this pr is currently branching off another fincap ticket, this is simply so that they can both go onto a qa environment together

[DEV APPROVED] 9589 search box update

---

app/assets/stylesheets/components/ui/_teaser.scss
app/assets/stylesheets/layout/common/_2_col.scss
app/assets/stylesheets/layout/common/_3_col.scss

[TP9654](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=bug/9654)
This addresses a bug in IE relating to the display of Flexbox child elements. 
The value ```flex: 1;``` defaults in IE differently to most browsers so the work here explicitly sets the flex value of child elements to ```flex: 1 1 auto;```
**Current** 
**Updated**

TP: 9654, Comment: Fixes Flexbug bug in IE

---

app/assets/javascripts/components/Cookie.js
app/assets/javascripts/require_config.js.erb
app/assets/stylesheets/components/ui/_all.scss
app/assets/stylesheets/components/ui/_cookie.scss
app/controllers/application_controller.rb
app/controllers/concerns/cookie_policy_acceptance.rb
app/controllers/cookie_policy_acceptances_controller.rb
app/views/shared/_header.html.erb
config/locales/en.yml
config/routes.rb
features/cookie_policy_acceptance.feature
features/step_definitions/cookie_policy_acceptance_steps.rb
features/step_definitions/homepage_steps.rb
features/step_definitions/shared_page_steps.rb
features/support/ui/page.rb
package.json
spec/controllers/concerns/cookie_police_acceptance_spec.rb
spec/javascripts/fixtures/Cookie.html
spec/javascripts/test-main.js
spec/javascripts/tests/Cookie_spec.js
spec/requests/cookie_policy_acceptances_spec.rb

[TP 9613](https://moneyadviceservice.tpondemand.com/entity/9613-implement-cookie-messaging)
This PR adds:
* A controller with an action to manage the creation of a permanent cookie
* A concern with a helper method to check the presence of the above cookie
* A conditional div displayed at the top of the header of every page
Front End 
Added a new javascript component (Cookie) to add the cookie using JS
Cookie is set to expire 20 years in the future as per the Rails version
Checked in Chrome, FF and Safari

[DEV APPROVED] - 9613 Add cookie message

---

app/views/shared/svg/_icon_sprite.html.erb

[TP9677](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiQzgxRjcwQTZCMjdGNDBDNzY0NzgxOEUwRjBFMjQ3NkQifQ==&boardPopup=bug/9677/silent)
This addresses a problem in IE with rendering the close icons across the site. The cause is a missing end tag in the SVG Sprite, which has the effect that they appear as below: 
This fix reverts them to the correct rendering:

[DEV APPROVED] TP: 9677, Comment: Adds missing end tag in SVG sprite

---

Dockerfile
Jenkinsfile

To improve Jenkins build times and general efficiency we can now pull a standard base image from our private Azure container registry. This removes the requirement to maintain explicit an Dockerfile across all our repos.
N.B The Dockerfile and docker-compose.yml are still available in the repo if there's additonal specific dependencies / requirements.

Use base image from private container registry

---

features/evidence_hub_search.feature
spec/cassettes/fincap_cms/get/api/en/documents_jsonblocks_identifier_year_of_publication_blocks_value_2019_blocks_value_2018_document_type_Insight_document_type_Evaluation_document_type_Review_keyword_page_1_per_page_20.yml

The test was failing as it checks for documents published in the
most recent 2 years. Originally the test was written in 2018 and
documents published in 2017 would be returned. Now that it is 2019,
2017 documents are no longer returned.
The fix was to update the seed data in the local cms to regenerate
the cassette.

Fix failing feature test

---

Gemfile.lock
app/views/layouts/application.html.erb
app/views/layouts/errors.html.erb
app/views/shared/_google_tag_manager.erb

[TP 10156](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&searchPopup=userstory/10156)
Display the google tag manager on the not found page.

[DEV APPROVED] 10156 Add the google tag manager script to the not_found page

---

Gemfile
config/environments/production.rb

[TP](https://moneyadviceservice.tpondemand.com/entity/10311-fin-cap-application-logging)
Use syslog in production instead of the Rails default logger.

Add syslog logger

---

app/assets/stylesheets/components/_footer.scss
app/views/shared/_twitter_feed.html.erb
app/views/shared/footer/_footer_social.html.erb
config/locales/en.yml
features/homepage.feature

[TP10948](https://maps.tpondemand.com/entity/10948-update-fincap-socials)
This PR updates social media links in three areas of the site: 
1) Footer: updates references to FinCap to Money and Pensions Service and updates the URLs. Additionally the width of the container has been increased to accommodate the additional text. 
2) The Twitter feed on articles pages. 
3) The 'Subscribe' newsletter link. There is no visible change here, the URL has been updated.

[DEV APPROVED] 10948 update socials

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/components/_all.scss
app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/components/_maps_banner.scss
app/assets/stylesheets/components/nav/_nav_level_1.scss
app/views/layouts/application.html.erb
app/views/shared/_maps_banner.html.erb
bower.json.erb
config/locales/en.yml
features/evidence_hub_search.feature

[TP11062](https://maps.tpondemand.com/entity/11062-add-maps-brand-banner-to-fincap)
This adds the MAPS banner to the Fin Cap site. This is very similar to the banner on MAS, with a few changes: 
- the text content is changed for Fin Cap
- the font retains the standard body size
- there are no variations in the rendering of the banner between the home page and other pages.

[DEV APPROVED] 11062 maps banner
